version: 0.0
os: linux
files:
  - source: src/api
    destination: /var/www/crm-lumen
  - source: src/web
    destination: /var/www/crm-vue
  - source: ./appspec.yml
    destination: /var/www/
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 900