version: '3.7'

volumes:
  src-web:
    driver_opts:
      type: none
      device: $PWD/src/web
      o: bind

services:
  db:
    container_name: ${APP_NAME}-mysql
    hostname: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./.docker/mysql/dump/:/docker-entrypoint-initdb.d/:rw

  adminer:
    container_name: ${APP_NAME}-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    container_name: ${APP_NAME}-web
    restart: always
    build:
      dockerfile: ./.docker/web/Dockerfile.local
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./src/web:/app
      - /app/node_modules

  php:
    container_name: ${APP_NAME}-php
    hostname: institucional-dev
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile.local
    working_dir: /var/www/html
    volumes:
      - ./src/api:/var/www/html
    ports:
      - 9000:9000
    environment:
      XDEBUG_CONFIG: remote_host=172.20.0.4
      PHP_XDEBUG_ENABLED: 1ss
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    depends_on:
      - db
    ports:
      - 9000:9000

  nginx:
    container_name: ${APP_NAME}-nginx
    hostname: nginx
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./src/api:/var/www/html
    build:
      dockerfile: ./.docker/nginx/Dockerfile.local
      context: .
    ports:
      - '8000:80'
      - '443:443'
    depends_on:
      - php

networks:
  default:
    name: ${APP_NAME}-network
