-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 23:43:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lumen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lumen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lumen` DEFAULT CHARACTER SET utf8 ;
USE `lumen` ;

-- -----------------------------------------------------
-- Table `lumen`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(15) NULL,
  `password` VARCHAR(255) NULL,
  `profile_id` INT NOT NULL,
  `cep` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `complement` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_USUARIO_PERFIL_USUARIO1_idx` (`profile_id` ASC) ,
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `EMAIL_UNIQUE` (`email` ASC) ,
  CONSTRAINT `fk_USUARIO_PERFIL_USUARIO1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `lumen`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `endpoint` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `refer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ENDPOINT_UNIQUE` (`endpoint` ASC) ,
  INDEX `fk_PAGINA_USUARIO1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_PAGINA_USUARIO1`
    FOREIGN KEY (`users_id`)
    REFERENCES `lumen`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MODELO_FABRICANTE1_idx` (`brand_id` ASC) ,
  CONSTRAINT `fk_MODELO_FABRICANTE1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `lumen`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `preco` DECIMAL(3,2) NULL,
  `ano` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PRODUTO_PAGINA1_idx` (`page_id` ASC) ,
  INDEX `fk_PRODUTO_MODELO1_idx` (`model_id` ASC) ,
  CONSTRAINT `fk_PRODUTO_PAGINA1`
    FOREIGN KEY (`page_id`)
    REFERENCES `lumen`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_MODELO1`
    FOREIGN KEY (`model_id`)
    REFERENCES `lumen`.`models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`leads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pages_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(45) NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `status_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `inserted_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LEADS_PAGINA1_idx` (`pages_id` ASC) ,
  INDEX `fk_LEAD_STATUS1_idx` (`status_id` ASC) ,
  INDEX `fk_LEAD_PRODUTO1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_LEADS_PAGINA1`
    FOREIGN KEY (`pages_id`)
    REFERENCES `lumen`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEAD_STATUS1`
    FOREIGN KEY (`status_id`)
    REFERENCES `lumen`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEAD_PRODUTO1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lumen`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`users_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`users_pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `pages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `pages_id`),
  INDEX `fk_USUARIO_PAGINA_USUARIO1_idx` (`users_id` ASC) ,
  INDEX `fk_USUARIO_PAGINA_PAGINA1_idx` (`pages_id` ASC) ,
  CONSTRAINT `fk_USUARIO_PAGINA_USUARIO1`
    FOREIGN KEY (`users_id`)
    REFERENCES `lumen`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_PAGINA_PAGINA1`
    FOREIGN KEY (`pages_id`)
    REFERENCES `lumen`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`products_shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`products_shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `shop_id`),
  INDEX `fk_PRODUTO_LOJA_PRODUTO1_idx` (`product_id` ASC) ,
  INDEX `fk_PRODUTO_LOJA_LOJA1_idx` (`shop_id` ASC) ,
  CONSTRAINT `fk_PRODUTO_LOJA_PRODUTO1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lumen`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_LOJA_LOJA1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `lumen`.`shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`historics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`historics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `historic` VARCHAR(45) NULL,
  `leads_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historics_leads1_idx` (`leads_id` ASC) ,
  CONSTRAINT `fk_historics_leads1`
    FOREIGN KEY (`leads_id`)
    REFERENCES `lumen`.`leads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lumen`.`leads_keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumen`.`leads_keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lead_id` INT NULL,
  `keyword_id` INT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`id`, `lead_id`, `keyword_id`, `product_id`),
  INDEX `fk_LEAD_KEYWORD_LEAD1_idx` (`lead_id` ASC) ,
  INDEX `fk_LEAD_KEYWORD_KEYWORD1_idx` (`keyword_id` ASC) ,
  INDEX `fk_LEAD_KEYWORD_PRODUTO1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_LEAD_KEYWORD_LEAD1`
    FOREIGN KEY (`lead_id`)
    REFERENCES `lumen`.`leads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEAD_KEYWORD_KEYWORD1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `lumen`.`keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEAD_KEYWORD_PRODUTO1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lumen`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `lumen`.`profiles` (`id`, `profile`) VALUES ('1', 'Administrador');
INSERT INTO `lumen`.`profiles` (`id`, `profile`) VALUES ('2', 'Usuário');