FROM node:12.18.3
LABEL maintainer="gabriel_ulbrich@outlook.com"

WORKDIR /app
COPY ./src/web/package.json .
RUN npm config set strict-ssl false
RUN npm install -g @vue/cli @vue/cli-service-global
COPY ./src/web/ .
EXPOSE 8080
CMD [ "npm", "run", "serve" ]