FROM node:12.18.3
LABEL maintainer="gabriel_ulbrich@outlook.com"

WORKDIR /app
COPY ./src/web/package.json .
RUN npm config set strict-ssl false
RUN npm install -g @vue/cli@latest @vue/cli-service-global
RUN npm install
COPY ./src/web/ .
EXPOSE 3000
CMD [ "npm", "run", "serve" ]